<?php

$xpdo_meta_map = array (
  'xPDOObject' => 
  array (
    0 => 'ActiveUsers',
    1 => 'ChunkTemplateSettings',
    2 => 'JotFields',
    3 => 'KeywordXref',
    4 => 'SiteContentMetatags',
    5 => 'SitePluginEvents',
    6 => 'SiteTmplvarTemplates',
    7 => 'SystemSettings',
    8 => 'Timetable',
    9 => 'TimetableCategories',
    10 => 'UserSettings',
    11 => 'WebUserSettings',
  ),
  'xPDOSimpleObject' => 
  array (
    0 => 'Categories',
    1 => 'DocumentGroups',
    2 => 'DocumentgroupNames',
    3 => 'EventLog',
    4 => 'FdCount',
    5 => 'JotContent',
    6 => 'JotSubscriptions',
    7 => 'Mailverteiler',
    8 => 'ManagerLog',
    9 => 'ManagerUsers',
    10 => 'Maxigallery',
    11 => 'MemberGroups',
    12 => 'MembergroupAccess',
    13 => 'MembergroupNames',
    14 => 'RegattaAktivenliste',
    15 => 'RegattaAltersklassen',
    16 => 'RegattaAusschreibung',
    17 => 'RegattaBootsklassen',
    18 => 'RegattaMeldungen',
    19 => 'RegattaStartZielzeiten',
    20 => 'RegattaVereine',
    21 => 'RgmEvents',
    22 => 'SiteContent',
    23 => 'SiteHtmlsnippets',
    24 => 'SiteKeywords',
    25 => 'SiteMetatags',
    26 => 'SiteModuleAccess',
    27 => 'SiteModuleDepobj',
    28 => 'SiteModules',
    29 => 'SitePlugins',
    30 => 'SiteSnippets',
    31 => 'SiteTemplates',
    32 => 'SiteTmplvarAccess',
    33 => 'SiteTmplvarContentvalues',
    34 => 'SiteTmplvars',
    35 => 'SystemEventnames',
    36 => 'Trainingszeiten',
    37 => 'UserAttributes',
    38 => 'UserMessages',
    39 => 'UserRoles',
    40 => 'WebGroups',
    41 => 'WebUserAttributes',
    42 => 'WebUserAttributesExtended',
    43 => 'WebUsers',
    44 => 'WebgroupAccess',
    45 => 'WebgroupNames',
  ),
);